# Generated by Django 4.2.30 on 2026-05-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('license_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveSmallIntegerField(default=40)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active / On Route'), ('idle', 'Idle'), ('maintenance', 'Under Maintenance'), ('out_of_service', 'Out of Service')], default='idle', max_length=20)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('current_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.SmallIntegerField(default=0, help_text='Degrees 0-359')),
                ('last_gps_update', models.DateTimeField(blank=True, null=True)),
                ('current_passengers', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_buses', to='routes.busstop')),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bus', to='accounts.driverprofile')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='routes.route')),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'db_table': 'buses',
                'ordering': ['bus_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_passengers', models.PositiveSmallIntegerField(default=0)),
                ('delay_minutes', models.SmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='accounts.driverprofile')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='routes.route')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_minutes', models.PositiveSmallIntegerField()),
                ('reason', models.CharField(choices=[('traffic', 'Heavy Traffic'), ('construction', 'Road Construction'), ('mechanical', 'Vehicle Maintenance Issue'), ('weather', 'Weather Conditions'), ('accident', 'Accident on Route'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('notified_students', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_reports', to='buses.bus')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delay_reports', to='buses.trip')),
            ],
            options={
                'db_table': 'delay_reports',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='BusMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('next_service', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='buses.bus')),
            ],
            options={
                'db_table': 'bus_maintenance_logs',
                'ordering': ['-date'],
            },
        ),
    ]
